version: "3.9"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secret_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./src/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3380:3306"

  backend:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: secret_app
    ports:
      - "3000:3000"
    command: npm run dev # or node dist/index.js if you're not using ts-node-dev
